services:
  - type: web
    name: movie-recommender-app
    env: python
    buildCommand: pip install --upgrade pip && pip install --use-pep517 -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.enableCORS=false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
